import type { GrammarDefinition } from "@effectstream/concise";
import { builtinGrammars } from "@effectstream/sm/grammar";
import { Type } from "@sinclair/typebox";

export const paimaL2Grammar = {
  schedule: [
    ["tick", Type.Integer()],
    [
      "type",
      Type.Union([
        Type.Literal("block"),
        Type.Literal("timestamp"),
      ]),
    ],
    ["message", Type.String()],
  ],
  // Scheduled input: fires at a future block when a lobby timeout expires.
  // Produced by createScheduledData() in the create_game STF.
  "werewolfLobbyTimeout": [
    ["gameId", Type.Number()],
  ],
  // Auto-lobby creation, posted to the batcher by the node as an EVM (paimaL2)
  // input — so it MUST live in paimaL2Grammar (the grammar the EVM primitive in
  // config.ts parses on-chain inputs with), not just the extended `grammar`.
  // encryptedGameSeed is a 128-char hex string (64 bytes: 32-byte salt + 32-byte
  // ciphertext) generated by the node using WEREWOLF_KEY_SECRET before posting.
  "autoCreateLobby": [["encryptedGameSeed", Type.String()]],
  // EVM Lobby API Grammars
  "create_game": [
    ["gameId", Type.Number()],
    ["maxPlayers", Type.Number()],
  ],
  "join_game": [
    ["gameId", Type.Number()],
    ["publicKey", Type.String()],
    ["nickname", Type.String()],
    ["appearanceCode", Type.Number()],
    ["midnightAddress", Type.String()],
  ],
  "close_game": [
    ["gameId", Type.Number()],
  ],
  "force_start": [
    ["gameId", Type.Number()],
  ],
  // Proxy wallet registration: records (evmAddress → proxyMidnightAddress) on-chain.
  // signerAddress (verified EVM) is the authoritative key — no extra field needed.
  "register_proxy_wallet": [
    ["proxyMidnightAddress", Type.String()],
  ],
  // Wallet claim: transfers leaderboard points from proxy Midnight address to real Lace address.
  // Only the EVM address that registered the proxy can submit this.
  "claim_real_wallet": [
    ["proxyMidnightAddress", Type.String()],
    ["realMidnightAddress", Type.String()],
  ],
  "game_state": [
    ["gameId", Type.Number()],
  ],
  "game_players": [
    ["gameId", Type.Number()],
  ],
} as const satisfies GrammarDefinition;

export const grammar = {
  ...paimaL2Grammar,
  "transfer-assets": builtinGrammars.evmErc721,
  "midnightContractState": [
    [
      "payload",
      Type.Object({
        // Define each ledger field from your Compact contract
        // The syncer will now know these are objects and will correctly unroll them
        Werewolf_games: Type.Any(),
        Werewolf_players: Type.Any(),
        Werewolf_roundVotes: Type.Any(),
        Werewolf_gameSecrets: Type.Any(),
        Werewolf_voteNullifiers: Type.Any(),
      }),
    ],
  ],
  // (autoCreateLobby moved into paimaL2Grammar above — it's an EVM input parsed by
  // the on-chain primitive, so it must be in paimaL2Grammar, not only here.)
  // Scheduled input: fires at a future block when a voting round times out.
  // Produced by createScheduledData() in the midnightContractState STF.
  "werewolfRoundTimeout": [
    ["gameId", Type.Number()],
    ["round", Type.Number()],
    ["phase", Type.String()],
  ],
} as const satisfies GrammarDefinition;

export * from "./types.ts";
